<TestLog><TestSuite name="Master Test Suite"><TestCase name="setup_error" file="error.cpp" line="42"><Info file="error.cpp" line="53"><![CDATA[check !c.running() has passed]]></Info><Info file="error.cpp" line="54"><![CDATA[check ec has passed]]></Info><Info file="error.cpp" line="55"><![CDATA[check ec.value() == 42 has passed]]></Info><Info file="error.cpp" line="68"><![CDATA[check se.code().value() == 24 has passed]]></Info><Info file="error.cpp" line="69"><![CDATA[check boost::starts_with(se.what(), "MyMessage") has passed]]></Info><Info file="error.cpp" line="71"><![CDATA[check has_thrown has passed]]></Info><TestingTime>0</TestingTime></TestCase><TestCase name="success_error" file="error.cpp" line="74"><Info file="error.cpp" line="86"><![CDATA[check !c.running() has passed]]></Info><Info file="error.cpp" line="87"><![CDATA[check ec has passed]]></Info><Info file="error.cpp" line="88"><![CDATA[check ec.value() == 22 has passed]]></Info><Info file="error.cpp" line="103"><![CDATA[check se.code().value() == 23 has passed]]></Info><Info file="error.cpp" line="104"><![CDATA[check boost::starts_with(se.what(), "MyMessage") has passed]]></Info><Info file="error.cpp" line="106"><![CDATA[check has_thrown has passed]]></Info><TestingTime>11000</TestingTime></TestCase><TestCase name="ignore_error" file="error.cpp" line="109"><Info file="error.cpp" line="113"><![CDATA[check 'no exceptions thrown by bp::child c("doesnt-exit", bp::ignore_error)' has passed]]></Info><TestingTime>2000</TestingTime></TestCase></TestSuite></TestLog>